services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    ports:
      - "3334:3306"
    volumes:
      - myVolume:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Arcenal2012
      MYSQL_DATABASE: world

volumes:
  myVolume:
    driver: local